### ISSUE TITLE
Failing to compile for iOS

### ISSUE THREAD

**Issue by zwells** [HyperSense-Software/hss-okta-flutter#55]
```Failed to build iOS app
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Switch must be exhaustive
/Users/zwells/.pub-cache/hosted/pub.dev/hss_okta_flutter-1.4.6/ios/Classes/HssOktaFlutterPlugin.swift:48:24

Xcode version: 16.2
Flutter version: 3.27.4

**Comment by aldrin233** [comment]
@andreineacsu #53 please merge

**Comment by aldrin233** [comment]
@zwells for now, you can add the branch #53 to fix the issue or wait for the lib to be published with the fix

```
hss_okta_flutter:
  git: 
    url: https://github.com/HyperSense-Software/hss-okta-flutter.git
    ref: ff582bd290605845be49c0a197127d7d7e1321aa
```
